# 
# docker-compose.yml — определяет сервисы для разработки и тестирования.

Что нужно сделать:
  - Настроить сервисы для:
      - PostgreSQL (или MySQL) с начальной базой.
      - Приложения Spring Boot (если нужно).
  - Открыть нужные порты (например, 5432, 8080).
  - Настроить volume для хранения данных БД.

services:

  db:
    image: postgres:16.1
    container_name: bank-rest-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=bankrest
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bank-rest-db